export const els = {
  appShell: document.getElementById("appShell"),
  sidebarBackdrop: document.getElementById("sidebarBackdrop"),
  sidebarToggle: document.getElementById("sidebarToggle"),
  navItems: [...document.querySelectorAll(".nav-item")],
  devNavBtn: document.getElementById("devNavBtn"),
  pageTitle: document.getElementById("pageTitle"),
  savePathLabel: document.getElementById("savePathLabel"),
  accentColorInput: document.getElementById("accentColorInput"),
  contentScroll: document.getElementById("contentScroll"),
  changePathBtn: document.getElementById("changePathBtn"),
  importBtn: document.getElementById("importBtn"),
  exportBtn: document.getElementById("exportBtn"),
  resetAllDataBtn: document.getElementById("resetAllDataBtn"),

  views: {
    hello: document.getElementById("view-hello"),
    inbox: document.getElementById("view-inbox"),
    tasks: document.getElementById("view-tasks"),
    projects: document.getElementById("view-projects"),
    daily: document.getElementById("view-daily"),
    dev: document.getElementById("view-dev"),
    settings: document.getElementById("view-settings")
  },

  helloLevelLabel: document.getElementById("helloLevelLabel"),
  helloLevelRing: document.getElementById("helloLevelRing"),
  helloXpLabel: document.getElementById("helloXpLabel"),
  helloXpHint: document.getElementById("helloXpHint"),
  helloXpTrack: document.getElementById("helloXpTrack"),
  helloXpBarFill: document.getElementById("helloXpBarFill"),
  helloTagStatsBlock: document.getElementById("helloTagStatsBlock"),
  helloTagStatsToggle: document.getElementById("helloTagStatsToggle"),
  helloTagStats: document.getElementById("helloTagStats"),
  helloRadarCanvas: document.getElementById("helloRadarCanvas"),
  radarZoomOutBtn: document.getElementById("radarZoomOutBtn"),
  radarZoomInBtn: document.getElementById("radarZoomInBtn"),
  activeTaskCount: document.getElementById("activeTaskCount"),
  helloActiveList: document.getElementById("helloActiveList"),
  helloProjectPeekList: document.getElementById("helloProjectPeekList"),
  helloDailyList: document.getElementById("helloDailyList"),

  inboxInput: document.getElementById("inboxInput"),
  inboxTagSelect: document.getElementById("inboxTagSelect"),
  inboxGroupSelect: document.getElementById("inboxGroupSelect"),
  inboxAddBtn: document.getElementById("inboxAddBtn"),
  inboxGroupTitleInput: document.getElementById("inboxGroupTitleInput"),
  inboxCreateGroupBtn: document.getElementById("inboxCreateGroupBtn"),
  inboxList: document.getElementById("inboxList"),

  tasksList: document.getElementById("tasksList"),

  createProjectBtn: document.getElementById("createProjectBtn"),
  projectTitleInput: document.getElementById("projectTitleInput"),
  projectTagSelect: document.getElementById("projectTagSelect"),
  projectsListScreen: document.getElementById("projectsListScreen"),
  projectDetailScreen: document.getElementById("projectDetailScreen"),
  projectDetailTitle: document.getElementById("projectDetailTitle"),
  projectBackBtn: document.getElementById("projectBackBtn"),
  projectsList: document.getElementById("projectsList"),
  projectDetails: document.getElementById("projectDetails"),

  dailyTemplateInput: document.getElementById("dailyTemplateInput"),
  dailyTemplateTagSelect: document.getElementById("dailyTemplateTagSelect"),
  dailyTemplateAddBtn: document.getElementById("dailyTemplateAddBtn"),
  dailyTemplatesList: document.getElementById("dailyTemplatesList"),

  devTagSelect: document.getElementById("devTagSelect"),
  devAddXpBtn: document.getElementById("devAddXpBtn"),
  devLevelUpBtn: document.getElementById("devLevelUpBtn"),
  devCompleteDailyBtn: document.getElementById("devCompleteDailyBtn"),

  tagInput: document.getElementById("tagInput"),
  tagAddBtn: document.getElementById("tagAddBtn"),
  tagsList: document.getElementById("tagsList"),

  winMinBtn: document.getElementById("winMinBtn"),
  winMaxBtn: document.getElementById("winMaxBtn"),
  winCloseBtn: document.getElementById("winCloseBtn")
};
